export const SECTIONS = [
  { id: 'file-sharing', label: 'File Sharing', color: '#0ea5e9' },
  { id: 'backups', label: 'Backups & DR', color: '#10b981' },
  { id: 'app-servers', label: 'App Servers', color: '#f59e0b' },
  { id: 'azure', label: 'Azure & Containers', color: '#8b5cf6' },
  { id: 'review', label: 'Midterm Review', color: '#ef4444' },
];

export const FLASHCARDS = {
  'file-sharing': [
    { term: 'SMB', def: 'Server Message Block — Microsoft\'s network file sharing protocol used for sharing files, printers, and serial ports. Default protocol for Windows file shares.' },
    { term: 'NFS', def: 'Network File System — Unix/Linux file sharing protocol. Permissions managed via /etc/exports using host-based access control (IP or hostname), not user auth like SMB.' },
    { term: 'DFS', def: 'Distributed File System — Microsoft technology that aggregates shared folders from multiple servers into a single unified namespace, improving availability and load balancing.' },
    { term: 'DACL', def: 'Discretionary Access Control List — The part of a security descriptor that specifies which users/groups are allowed or denied access to an object. What you see in the Security tab of a file\'s Properties.' },
    { term: 'SACL', def: 'System Access Control List — Controls auditing. Specifies which access attempts (success/fail) get logged to the Security event log. Separate from DACL.' },
    { term: 'Effective Access', def: 'The actual permissions a user has to a resource after combining ALL sources: NTFS + share permissions + group memberships + explicit deny rules. Most restrictive between share and NTFS wins.' },
    { term: 'Encrypting File System (EFS)', def: 'Windows feature that encrypts files/folders at the filesystem level using the user\'s certificate. Only the encrypting user (and designated recovery agents) can decrypt. Survives copying if staying on NTFS.' },
    { term: 'UNC Path', def: 'Universal Naming Convention path — format: \\\\ServerName\\ShareName\\path\\to\\file. Used to access network shares without mapping a drive letter.' },
    { term: 'Mapping a Drive', def: 'Assigning a local drive letter (e.g. Z:) to a UNC network path so users can access it like a local drive. Can be done via File Explorer or "net use Z: \\\\server\\share".' },
    { term: 'User/Folder Quota', def: 'Limits on how much disk space a user or folder can consume on a volume. Enforced by Windows File Server Resource Manager (FSRM). Can be hard (blocks writes) or soft (warns only).' },
    { term: 'Offline File Caching', def: 'Feature that lets users access shared folder contents when not connected to the network. Configured per-share via the Caching settings. Syncs when reconnected.' },
    { term: 'File Explorer', def: 'Windows GUI tool for browsing files and folders, managing permissions via the Security tab, mapping drives, and accessing network shares.' },
    { term: 'File Attributes', def: 'Metadata flags on a file: Read-Only, Hidden, System, Archive (marks file as changed since last backup). Advanced: Compress, Encrypt, Index.' },
  ],
  'backups': [
    { term: 'RAID', def: 'Redundant Array of Independent Disks — hardware/software solution for disk redundancy and/or performance. NOT a backup — protects against drive failure only, not accidental deletion, ransomware, or corruption.' },
    { term: 'Full Backup', def: 'Copies all selected data regardless of the archive attribute. Clears the archive bit after. Slowest to perform, fastest to restore from (single backup set needed).' },
    { term: 'Incremental Backup', def: 'Copies only files changed since the LAST backup (full OR incremental). Clears the archive bit. Fastest to perform, slowest to restore (need full + all incrementals in sequence).' },
    { term: 'Bare Metal Recovery', def: 'Restoring a complete system — OS, apps, settings, data — to brand new hardware from a backup image. Gets a machine back to fully operational state without reinstalling anything.' },
    { term: 'System State', def: 'A Windows Backup target that captures critical system components: Registry, COM+ class registration, boot files, Active Directory (on DCs), Certificate Services. Used for system recovery without full bare metal.' },
    { term: 'Windows Server Backup', def: 'Built-in Windows Server backup tool. Supports full server backups, volumes, system state, and bare metal recovery. Limited: stores only 1 copy of full backup and allows max 512 incrementals before requiring a new full.' },
    { term: 'Backup Schedule', def: 'Automated timing configuration for when backups run. Windows Server Backup supports daily schedules. Critical for RTO/RPO compliance.' },
    { term: 'Archive Attribute', def: 'File flag that indicates a file has been modified since the last backup. Full backups clear it on all files; incremental backups only copy and clear files that have it set.' },
  ],
  'app-servers': [
    { term: 'IIS', def: 'Internet Information Services — Microsoft\'s web server built into Windows Server. Managed via IIS Manager. Default web root: C:\\inetpub\\wwwroot. Default log location: C:\\inetpub\\logs\\LogFiles.' },
    { term: 'Apache', def: 'Open-source web server (Apache HTTP Server). Dominant on Linux. Default web root: /var/www/html. Config syntax check: apache2ctl configtest or apachectl -t.' },
    { term: 'Application Pools', def: 'IIS isolation mechanism — each app pool runs in its own worker process (w3wp.exe) with its own identity and settings. Crashes in one pool don\'t affect others. One pool can serve multiple sites.' },
    { term: 'Site Bindings', def: 'IIS configuration linking a website to a specific IP, port, and/or host header (domain name). Allows multiple sites on one server using different ports or host headers. HTTP = port 80, HTTPS = port 443.' },
    { term: 'Default Document', def: 'The file IIS or Apache serves when a request doesn\'t specify a filename (e.g., visiting http://example.com/ serves index.html). Configurable list with priority order.' },
    { term: 'FTP', def: 'File Transfer Protocol — used to upload/download files to/from a server. Runs on port 21 (control) and port 20 (data). IIS supports FTP sites alongside web sites.' },
    { term: 'Certificate', def: 'SSL/TLS certificate used for HTTPS. Binds a public key to a domain name, verified by a Certificate Authority (CA). Required to configure a site binding over HTTPS (port 443).' },
    { term: 'DNS', def: 'Domain Name System — resolves human-readable names to IP addresses. A web server needs a DNS A record pointing its domain to the server\'s IP for the site to be reachable by name.' },
    { term: 'Port', def: 'Logical endpoint for network communication. HTTP = 80, HTTPS = 443. Non-standard ports require a firewall rule to be opened and users must specify the port in the URL (e.g., http://server:8080).' },
    { term: 'Firewall Rules', def: 'Allow/deny rules controlling which network traffic reaches the server. When using a non-default port for a website, a firewall inbound rule must be created to allow that port\'s traffic.' },
    { term: 'Web Application', def: 'A software application delivered over HTTP/HTTPS via a web browser. In IIS, a web application is a sub-component of a website with its own application pool and settings.' },
    { term: 'Error Pages', def: 'Custom pages shown when HTTP errors occur (404 Not Found, 500 Internal Server Error, etc.). Configured in IIS to show user-friendly messages instead of raw error details, hiding server internals.' },
    { term: 'IIS Manager', def: 'The GUI management console for IIS. Used to configure sites, application pools, bindings, SSL certificates, authentication, error pages, default documents, and more.' },
  ],
  'azure': [
    { term: 'Azure Virtual Machine', def: 'IaaS offering — a VM running in Microsoft\'s datacenter. You manage the OS and above; Microsoft manages physical hardware. Supports Windows and Linux. Can run any workload a physical server can.' },
    { term: 'Azure App Service', def: 'PaaS offering for hosting web apps, REST APIs, and mobile backends. No OS management required. Supports .NET, Java, Node.js, Python, PHP. Deployed via Git, ZIP, FTP, or Azure DevOps.' },
    { term: 'Azure Function', def: 'Serverless compute — runs code in response to events (HTTP trigger, timer, queue message) without provisioning servers. Pay only for execution time. Great for event-driven, short-lived tasks.' },
    { term: 'Entra ID', def: 'Microsoft\'s cloud identity platform (formerly Azure AD). Provides SSO, MFA, and identity management for Azure services. Connects to on-prem AD via hybrid join. Central auth hub for all Azure tools.' },
    { term: 'Intune', def: 'Microsoft\'s cloud-based MDM/MAM solution. Manages devices (Windows, iOS, Android, macOS) and enforces compliance policies. Integrates with Entra ID for conditional access.' },
    { term: 'Azure Blob Storage', def: 'Object storage for unstructured data (images, videos, backups, logs). Organized into Containers within Storage Accounts. Three access tiers: Hot, Cool, Archive.' },
    { term: 'Azure Files', def: 'Fully managed cloud file shares accessible via SMB or NFS protocol. Can be mounted on Windows, Linux, macOS. Can replace or supplement on-prem file servers.' },
    { term: 'Azure Backup', def: 'Cloud-based backup service. Benefits: offsite by default, unlimited storage scaling, geo-redundancy, no hardware maintenance. Limitation vs. traditional: requires internet, potential egress costs, slower restore for large data.' },
    { term: 'Resource Group', def: 'A logical container in Azure that holds related Azure resources (VMs, storage, networking) for a project or solution. Used for access control, billing, and lifecycle management.' },
    { term: 'Container Image', def: 'A read-only template containing the app, runtime, libraries, and config needed to run a container. Built from a Dockerfile. Stored in a registry (Docker Hub, Azure Container Registry).' },
    { term: 'WSL', def: 'Windows Subsystem for Linux — lets you run a Linux environment (bash shell, GNU tools, Linux apps) directly on Windows without a VM or dual boot. Used for development and cross-platform tooling.' },
    { term: 'Azure Blob Storage (Containers)', def: 'Not the same as Docker containers — in Azure Storage, a "container" is a logical grouping of blobs (files) within a storage account. Different concept, same word.' },
  ],
  'review': [
    { term: 'Windows Workgroup', def: 'Peer-to-peer network model. Each PC manages its own user accounts locally. No central authentication. Works fine for small networks (<10 PCs). No GPO, no centralized management.' },
    { term: 'Windows Domain', def: 'Client-server network with a Domain Controller running Active Directory. Centralized user accounts, GPO, and authentication. Required for enterprise management. PCs "join" the domain.' },
    { term: 'APIPA Address', def: 'Automatic Private IP Addressing — 169.254.x.x/16. Assigned by Windows when DHCP fails. Indicates the PC cannot reach a DHCP server. Only allows local-link communication, not internet or most LAN traffic.' },
    { term: 'Static IP', def: 'Manually configured IP address that doesn\'t change. Used for servers, printers, and infrastructure devices. Required config: IP, subnet mask, default gateway, DNS server.' },
    { term: 'Dynamic IP (DHCP)', def: 'IP address automatically leased from a DHCP server. Can change over time. Used for client workstations. Server hands out IP, subnet, gateway, and DNS automatically.' },
    { term: 'Minimum Network Settings', def: 'For basic network communication: IP address + subnet mask. To reach other networks: + default gateway. For name resolution: + DNS server address.' },
    { term: 'Active Directory OU', def: 'Organizational Unit — container within AD for organizing users, computers, and groups. GPOs can be linked to OUs. Allows delegated administration and policy scoping.' },
    { term: 'FQDN', def: 'Fully Qualified Domain Name — complete domain name (e.g., server01.corp.example.com). Verify resolution via nslookup server01.corp.example.com or ping by FQDN from a domain member.' },
    { term: 'GPO Update Interval', def: 'Group Policy refreshes every 90 minutes by default (+ random 0–30 min offset) on workstations; every 5 minutes on Domain Controllers. Force update with: gpupdate /force.' },
    { term: 'GPO Application Order', def: 'LSDOU — Local → Site → Domain → OU (innermost last). Later-applied policies override earlier ones for conflicting settings. OU policy wins over domain policy.' },
    { term: 'Local vs Domain User Accounts', def: 'Local accounts: stored on the individual PC, only work on that machine. Domain accounts: stored in AD on the DC, work on any domain-joined machine. Domain accounts get GPO, roaming profiles, etc.' },
  ],
};

export const QUIZ_QUESTIONS = [
  {
    section: 'file-sharing',
    question: 'A user has NTFS Read permission and Share Full Control on a folder. What is their effective access when connecting over the network?',
    options: ['Full Control', 'Read', 'No Access', 'Modify'],
    answer: 1,
    explanation: 'Effective network access = most restrictive of NTFS and Share permissions. NTFS Read ∩ Share Full Control = Read.',
  },
  {
    section: 'file-sharing',
    question: 'A user is explicitly Denied Read on a file but their group is Allowed Read. What happens?',
    options: ['They can read (group allow wins)', 'They cannot read (explicit deny wins)', 'Access depends on which was set first', 'They get prompted for a password'],
    answer: 1,
    explanation: 'Deny always takes precedence over Allow in Windows NTFS permissions, regardless of group membership.',
  },
  {
    section: 'file-sharing',
    question: 'You copy a file from C:\\Folder1 to C:\\Folder2 on the same NTFS volume. What permissions does the copied file have?',
    options: ['It keeps its original permissions', 'It inherits permissions from Folder2', 'It has no permissions (must be set manually)', 'It inherits from Folder1'],
    answer: 1,
    explanation: 'Copied files always inherit permissions from the destination folder, even on the same volume. Moved files on the same volume keep their original permissions.',
  },
  {
    section: 'file-sharing',
    question: 'You move a file from C:\\Folder1 to C:\\Folder2 on the SAME NTFS volume. What permissions does it have?',
    options: ['It inherits from Folder2', 'It keeps its original permissions', 'Permissions are lost', 'It inherits from Folder1'],
    answer: 1,
    explanation: 'Moving within the same volume preserves original permissions. Moving to a DIFFERENT volume acts like a copy — inherits from destination.',
  },
  {
    section: 'file-sharing',
    question: 'What permission level allows a user to view file names in a folder but NOT open or read those files?',
    options: ['Read', 'List Folder Contents', 'Traverse Folder', 'Read & Execute'],
    answer: 1,
    explanation: 'List Folder Contents allows seeing the names of files and subfolders but not opening or reading file contents.',
  },
  {
    section: 'file-sharing',
    question: 'How do you create a hidden share on Windows Server?',
    options: ['Prefix the share name with a dot (.)', 'Append a $ to the share name', 'Check "Hidden" in share properties', 'Set the Hidden file attribute on the folder'],
    answer: 1,
    explanation: 'Appending $ to a share name (e.g., FinanceData$) hides it from browse lists. Users must know the exact UNC path: \\\\server\\FinanceData$',
  },
  {
    section: 'file-sharing',
    question: 'How are NFS share permissions managed differently from SMB share permissions?',
    options: ['NFS uses Active Directory user accounts', 'NFS uses host-based access control (IP/hostname) via /etc/exports', 'NFS permissions are set in Windows Security tab', 'NFS requires a separate license'],
    answer: 1,
    explanation: 'NFS grants access based on client IP addresses or hostnames (configured in /etc/exports on Linux), not per-user credentials like SMB/Windows.',
  },
  {
    section: 'file-sharing',
    question: 'Which Active Directory object types CAN be assigned NTFS permissions?',
    options: ['Only individual users', 'Only security groups', 'Users, security groups, and computer accounts', 'Users and distribution groups'],
    answer: 2,
    explanation: 'NTFS permissions can be assigned to users, security groups, and computer accounts. Distribution groups (email lists) cannot be assigned security permissions.',
  },
  {
    section: 'file-sharing',
    question: 'A user wants to work on shared files from home while offline. What share setting must be configured?',
    options: ['Enable SMBv2 on the share', 'Configure Offline File Caching (Always Available Offline)', 'Set the share to Read-only', 'Enable Shadow Copies'],
    answer: 1,
    explanation: 'Offline File Caching (configured in the share\'s Caching settings) allows users to access and work on files offline, syncing changes when reconnected.',
  },
  {
    section: 'backups',
    question: 'How many incremental backups does Windows Server Backup allow before requiring a new full backup?',
    options: ['64', '128', '256', '512'],
    answer: 3,
    explanation: 'Windows Server Backup allows up to 512 incremental backups before requiring a new full backup. It also only stores one full backup copy.',
  },
  {
    section: 'backups',
    question: 'Which backup type is fastest to PERFORM?',
    options: ['Full backup', 'Incremental backup', 'Differential backup', 'System state backup'],
    answer: 1,
    explanation: 'Incremental is fastest to perform (only changed files since last backup). Full is slowest to perform but fastest to restore.',
  },
  {
    section: 'backups',
    question: 'Which backup type is fastest to RESTORE FROM?',
    options: ['Full backup', 'Incremental backup', 'System state backup', 'Shadow copy'],
    answer: 0,
    explanation: 'Full backup restores in one pass. Incremental requires the full backup + every incremental in sequence, which takes much longer.',
  },
  {
    section: 'backups',
    question: 'Is RAID an effective comprehensive backup strategy?',
    options: ['Yes — it provides redundancy so no backup needed', 'No — RAID only protects against drive failure, not deletion or ransomware', 'Yes — RAID 5 provides full backup capability', 'It depends on the RAID level'],
    answer: 1,
    explanation: 'RAID protects against physical drive failure only. It does NOT protect against accidental deletion, ransomware, corruption, or site disasters. Always use RAID + backups.',
  },
  {
    section: 'backups',
    question: 'What is the key difference between NFS and DFS?',
    options: ['NFS is for backups, DFS is for file sharing', 'NFS is a cross-platform file sharing protocol; DFS is a Microsoft namespace that aggregates multiple shares', 'NFS works on Windows, DFS works on Linux', 'They are the same technology with different names'],
    answer: 1,
    explanation: 'NFS (Network File System) is a cross-platform file sharing PROTOCOL (Linux/Unix origin). DFS (Distributed File System) is a Microsoft NAMESPACE technology that unifies multiple share locations under one path.',
  },
  {
    section: 'backups',
    question: 'Do files restored from a Windows Server Backup retain their original permissions?',
    options: ['Yes, always', 'No, they lose all permissions', 'Yes, NTFS permissions are preserved in the backup', 'Only if restored to the same server'],
    answer: 2,
    explanation: 'Yes — Windows Server Backup preserves NTFS permissions. Restored files have the same permissions they had when backed up.',
  },
  {
    section: 'app-servers',
    question: 'What is the default web root directory for IIS?',
    options: ['/var/www/html', 'C:\\inetpub\\wwwroot', 'C:\\Windows\\IIS\\www', 'C:\\Program Files\\IIS\\root'],
    answer: 1,
    explanation: 'IIS default web root is C:\\inetpub\\wwwroot. Default log location is C:\\inetpub\\logs\\LogFiles.',
  },
  {
    section: 'app-servers',
    question: 'What command checks for Apache configuration syntax errors?',
    options: ['iisreset /check', 'apache2ctl configtest (or apachectl -t)', 'apache --validate', 'systemctl check apache2'],
    answer: 1,
    explanation: 'apache2ctl configtest (Debian/Ubuntu) or apachectl -t (other distros) parses the config and reports syntax errors without restarting the service.',
  },
  {
    section: 'app-servers',
    question: 'You host two websites on one IIS server. What must be true about their port assignments?',
    options: ['They must use the same port', 'They must use different ports OR different host headers (domain names)', 'Each site needs its own IP address', 'They must use different application pools'],
    answer: 1,
    explanation: 'IIS differentiates sites by port, hostname (host header), or IP address. Two sites can share port 80 if they have different host headers (domain names), or use different ports.',
  },
  {
    section: 'app-servers',
    question: 'What DNS record type maps a new domain name to an IP address for a web server?',
    options: ['MX record', 'CNAME record', 'A record', 'PTR record'],
    answer: 2,
    explanation: 'An A record (Address record) maps a hostname/domain to an IPv4 address. This is what you create when pointing a new domain to your web server\'s IP.',
  },
  {
    section: 'app-servers',
    question: 'When hosting a site on a non-default port (e.g., 8080), what additional step is required for it to be reachable from other computers?',
    options: ['Change the site binding to HTTPS', 'Create an inbound firewall rule allowing that port', 'Install a new SSL certificate', 'Add a second network adapter'],
    answer: 1,
    explanation: 'Non-standard ports are blocked by Windows Firewall by default. You must create an inbound rule to allow traffic on that port (e.g., TCP 8080).',
  },
  {
    section: 'app-servers',
    question: 'What is the purpose of IIS Error Pages?',
    options: ['To log all HTTP errors to a database', 'To show user-friendly messages instead of raw server error details', 'To redirect users to a different site on error', 'To block malicious requests'],
    answer: 1,
    explanation: 'Custom error pages present friendly messages (e.g., "Page Not Found") instead of exposing server internals and stack traces to end users — improving both UX and security.',
  },
  {
    section: 'azure',
    question: 'Which Azure service is used to host websites and web applications (PaaS)?',
    options: ['Azure Virtual Machines', 'Azure App Service', 'Azure Blob Storage', 'Azure Functions'],
    answer: 1,
    explanation: 'Azure App Service is the PaaS offering for web apps. You deploy code, Microsoft manages the underlying infrastructure. Deployed via Git, ZIP deploy, or Azure DevOps.',
  },
  {
    section: 'azure',
    question: 'What is a primary benefit of Azure Backup over traditional on-premises backup?',
    options: ['Faster restore speeds', 'Offsite storage, geo-redundancy, and no hardware to manage', 'Lower cost in all scenarios', 'No internet connection required'],
    answer: 1,
    explanation: 'Azure Backup is offsite by default, scales automatically, provides geo-redundant storage, and eliminates backup hardware costs and maintenance.',
  },
  {
    section: 'azure',
    question: 'What Docker command creates a container WITHOUT starting it?',
    options: ['docker run', 'docker create', 'docker init', 'docker build'],
    answer: 1,
    explanation: '"docker create" creates a container from an image without starting it. "docker run" creates AND starts. You can then start it later with "docker start <container>".',
  },
  {
    section: 'azure',
    question: 'What must you do to a container before it can be deleted?',
    options: ['Commit it to an image first', 'Stop it', 'Remove all volumes attached to it', 'Export its logs'],
    answer: 1,
    explanation: 'A running container cannot be deleted. You must stop it first (docker stop <container>), then remove it (docker rm <container>). Or use docker rm -f to force-delete a running container.',
  },
  {
    section: 'azure',
    question: 'What is the primary difference between a VM and a container?',
    options: ['VMs are faster to start', 'Containers share the host OS kernel; VMs run a full guest OS', 'Containers require more resources', 'VMs cannot run on cloud platforms'],
    answer: 1,
    explanation: 'Containers share the host OS kernel (lightweight, fast start). VMs include a full guest OS (heavier, stronger isolation). Containers are more portable; VMs provide stronger isolation.',
  },
  {
    section: 'azure',
    question: 'What is the purpose of Windows Subsystem for Linux (WSL)?',
    options: ['To replace Windows entirely with Linux', 'To run Linux tools and a bash environment directly on Windows without a VM', 'To virtualize Windows on Linux hosts', 'To manage Azure Linux VMs from Windows'],
    answer: 1,
    explanation: 'WSL lets developers run Linux bash shells, command-line tools, and even GUI apps directly on Windows. No VM or dual-boot required. Integrates with Windows filesystem.',
  },
  {
    section: 'review',
    question: 'What is an APIPA address and what does it indicate?',
    options: ['A static address for servers (192.168.x.x)', 'A 169.254.x.x address assigned when DHCP fails — indicates no DHCP server was reachable', 'A public IP assigned by the ISP', 'A loopback address for local testing'],
    answer: 1,
    explanation: 'APIPA (169.254.0.0/16) is auto-assigned when a Windows PC cannot reach a DHCP server. It means the DHCP request failed. Limited to local-link only — no internet or routing.',
  },
  {
    section: 'review',
    question: 'What happens to a computer\'s local Administrators group when it joins a domain?',
    options: ['The local admin account is deleted', 'The Domain Admins group is automatically added to the local Administrators group', 'Local accounts are migrated to AD', 'The local Administrators group is removed'],
    answer: 1,
    explanation: 'When joining a domain, the Domain Admins global group is automatically added to the local Administrators group on the computer, granting domain admins local admin rights.',
  },
  {
    section: 'review',
    question: 'In what order are Group Policies applied?',
    options: ['Domain → Site → OU → Local', 'Local → Site → Domain → OU (innermost last)', 'OU → Domain → Site → Local', 'Random order based on when they were created'],
    answer: 1,
    explanation: 'LSDOU: Local → Site → Domain → OU. Later-applied policies override earlier ones for conflicting settings. The innermost OU policy is applied last and has highest precedence.',
  },
  {
    section: 'review',
    question: 'How often do GPO settings refresh by default on workstations?',
    options: ['Every 15 minutes', 'Every 90 minutes (+ 0–30 min random offset)', 'Every 4 hours', 'Only at login'],
    answer: 1,
    explanation: 'Default refresh interval is 90 minutes with a random offset of 0–30 minutes to prevent all machines hitting the DC simultaneously. Force refresh with: gpupdate /force.',
  },
  {
    section: 'review',
    question: 'What are the minimum settings a computer needs to communicate on a local network?',
    options: ['IP address only', 'IP address and subnet mask', 'IP address, subnet mask, and default gateway', 'IP address, subnet mask, gateway, and DNS'],
    answer: 1,
    explanation: 'Minimum for local network communication: IP address + subnet mask. You need a default gateway to reach other networks, and DNS for name resolution — but those aren\'t needed for basic local comms.',
  },
];
